FROM ubuntu:22.04

RUN apt update \
    && apt install -y \
    g++ \
    clang \
    cmake \
    clang-format \
    clang-tidy \
    lcov \
    build-essential \
    libx11-dev \
    libfreetype-dev \
    libfontconfig-dev \
    libxinerama-dev \
    libxft-dev \
    lzma \
    valgrind

ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID -o dmenu
RUN useradd -m -u $UID -g $GID -o -s /bin/bash dmenu

USER dmenu

WORKDIR /dmenu
