name: Ubuntu24

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
       - '**'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: FetchSubmodules
      run: |
        git submodule init
        git submodule update

    - name: g++ Release
      run: make build

    - name: g++ Unit
      run: make unit

    - name: g++ Coverage
      run: make coverage

    - name: g++ Valgrind
      run: make valgrind

    - name: clang++ Unit
      run: make unit CC=clang CXX=clang++

    - name: clang++ Valgrind
      run: make valgrind CC=clang CXX=clang++

    - name: clang++ Release
      run: make build CC=clang CXX=clang++

